root = "."
tmp_dir = "tmp"

[build]
# Use the Makefile's build command
cmd = "make build"
env_file = ".env.tmp"
# The binary will be in the build directory as specified in your Makefile
bin = "build/appointment-service"
include_ext = ["go", "mod", "sum"]
exclude_dir = ["tmp", "vendor", "build", "testdata"]
exclude_regex = ["_test.go"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = "0.5s"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
